#+TITLE: Trevoke's emacs config
#+OPTIONS: toc:4 h:4

* Configuration
** TODO new organization
I should set up this file in a more goal-oriented manner.

There is the dependency of setting up the package manager (which maybe one day I'll remove entirely, but right now Cask+pallet is too damn nice).

After that, I want something like:

*** Navigating code
*** Navigating filesystem
*** Taking notes
*** Generating content
*** Uncategorized (which will have things like calendar and such
** About (actually put text in here)
<<babel-init>>
I came to emacs after vim and Rubymine. I love how it's all buffers.
** Personal information
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Aldric Giacomoni"
      user-mail-address "trevoke@gmail.com")
#+END_SRC
** Additional paths
This is mostly necessary for things not handled by Cask (which we'll see later down the line)
*** Themes
#+BEGIN_SRC emacs-lisp
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
#+END_SRC
*** Packages
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/packages")
#+END_SRC
*** TODO Secrets (configure paradox)
API keys, passwords, etc are kept in here. This file is .gitignored.
#+BEGIN_SRC emacs-lisp
(load "~/.emacs.d/emacs.secrets" t)
#+END_SRC
** Customizations from customization system
Keeping these separate makes life easier: they get modified when I load a theme and such, and I don't need that kind of hassle when maintaining my actual configuration, you know?
In addition, I do keep some somewhat computer-specific stuff in there, like the font, and it's just easier to have this separated there.
#+BEGIN_SRC emacs-lisp
(setq custom-file "~/.emacs-custom.el")
(load custom-file)
#+END_SRC
** Package manglement
I use Cask. I enjoy the declarative, Gemfile- or puppet-like approach.
#+BEGIN_SRC emacs-lisp
(require 'cask "~/.cask/cask.el")
(cask-initialize)
(require 'pallet)
(pallet-mode t)
#+END_SRC
** Packages
*** Anzu (about search results)
#+BEGIN_SRC emacs-lisp
(global-anzu-mode t)
(global-set-key (kbd "M-%") 'anzu-query-replace)
(global-set-key (kbd "C-M-%") 'anzu-query-replace-regexp)
#+END_SRC
*** Smart mode line
#+BEGIN_SRC emacs-lisp
(setq sml/theme 'dark)
(sml/setup)
#+END_SRC
*** Expand region
One of the features that makes IDEA's editors awesome is the way you can expand selection. This plugin replicates the feature.
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c <up>") 'er/expand-region)
(global-set-key (kbd "C-c <down>") 'er/contract-region)
#+END_SRC
*** projectile-mode
#+BEGIN_SRC emacs-lisp
(require 'projectile)
(projectile-global-mode)
(setq projectile-completion-system 'grizzl)
#+END_SRC
*** Wgrep-ag
Sometimes after you've found a bunch of things, you want to edit.. Kind of a find-and-replace sort of deal, maybe?
#+BEGIN_SRC emacs-lisp
(autoload 'wgrep-agp-setup "wgrep-ag")
(add-hook 'ag-mode-hook 'wgrep-ag-setup)
#+END_SRC
*** Guide key
emacs is awesome. It's also crazy, crazy full-featured. This plugin lets you examine what's behind the door of a key prefix.
#+BEGIN_SRC emacs-lisp
(setq guide-key/guide-key-sequence
      '("C-x r" "C-x 4" "C-h" "C-c"
              "C-x" "C-x a" "C-x C-a"
              "C-x 8" "C-x 8 \"  " "C-x 8 '" "C-x 8 ~"
              "C-u" "C-u C-x"))
(guide-key-mode 1)
#+END_SRC
*** Discover
On the topic of discovering emacs.. Discover.el is amazing.
#+BEGIN_SRC emacs-lisp
(global-discover-mode 1)
#+END_SRC
*** Snippets
Snippets; when you've tried 'em, it's hard to do without 'em. I mean, keystrokes, who needs 'em, right?
#+BEGIN_SRC emacs-lisp
(yas-global-mode 1)
#+END_SRC
*** Git
Magit for the win.
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "\C-c g") 'magit-status)
(setq magit-last-seen-setup-instructions "1.4.0") ;; magit auto-reverts unmodified buffers
#+END_SRC
*** Default text scale
This handy little package increases the size of the font in the whole frame.
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-=") 'default-text-scale-increase)
(global-set-key (kbd "C-x C--") 'default-text-scale-decrease)
#+END_SRC
*** Playing MUDs
#+BEGIN_SRC emacs-lisp
(autoload 'mu-open "mu" "Play on MUSHes and MUDs" t)
(add-hook 'mu-connection-mode-hook 'ansi-color-for-comint-mode-on)
#+END_SRC
*** Auto completion
#+BEGIN_SRC emacs-lisp
(eval-after-load 'auto-complete
  '(add-to-list 'ac-modes 'inf-ruby-mode))
(add-hook 'inf-ruby-mode-hook 'ac-inf-ruby-enable)

(eval-after-load 'inf-ruby
  '(define-key inf-ruby-mode-map (kbd "TAB") 'auto-complete))

(require 'auto-complete-config)
(ac-config-default)
#+END_SRC emacs-lisp
*** Mew (email)
Mew's config is in ~/.mew.el so you won't see it here. Nee-ner nee-ner nee-----ner.
#+BEGIN_SRC emacs-lisp
(autoload 'mew "mew" nil t)
(autoload 'mew-send "mew" nil t)

;; Optional setup (Read Mail menu):
(setq read-mail-command 'mew)

;; Optional setup (e.g. C-xm for sending a message):
(autoload 'mew-user-agent-compose "mew" nil t)
(if (boundp 'mail-user-agent)
    (setq mail-user-agent 'mew-user-agent))
(if (fboundp 'define-mail-user-agent)
    (define-mail-user-agent
      'mew-user-agent
      'mew-user-agent-compose
      'mew-draft-send-message
      'mew-draft-kill
      'mew-send-hook))

(setq mew-use-master-passwd t)
#+END_SRC
*** Blogging
#+BEGIN_SRC emacs-lisp
(require 'org-page)
(setq op/repository-directory "~/src/projects/trevoke.github.io")
(setq op/personal-github-link "https://github.com/trevoke")
(setq op/site-domain "http://blog.trevoke.net/")
(setq op/site-main-title "Seven Steps")
(setq op/site-sub-title "Words... words, they're all we have to go on! - Rosencrantz and Guildenstern are dead")
#+END_SRC
** Programming
*** First, MY hook
You know, just the stuff I want enabled in any code buffer.
#+BEGIN_SRC emacs-lisp
(defun stag-code-modes-hook ()
  (projectile-mode)
  (linum-mode t)
  (smartparens-mode)
  (auto-complete-mode)
  (ggtags-mode)
  (eldoc-mode)
  (hs-minor-mode t)
  (add-hook 'before-save-hook 'whitespace-cleanup)
  (local-set-key "\C-m" 'newline-and-indent))
#+END_SRC
*** Log files
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.log\\'" . auto-revert-mode))
#+END_SRC
*** ggtags
This is the ggtags plugin, which uses GNU Global.
#+BEGIN_SRC emacs-lisp
(setq tags-case-fold-search nil)
(global-set-key (kbd "<f7>") 'ggtags-create-tags)
#+END_SRC
*** C++
#+BEGIN_SRC emacs-lisp
(add-hook 'c++-mode-hook 'stag-code-modes-hook)
#+END_SRC
*** C#
#+BEGIN_SRC emacs-lisp
(defun stag-csharp-mode-hook ()
  (setq c-basic-offset 4))

(add-hook 'csharp-mode-hook 'stag-code-modes-hook)
(add-hook 'csharp-mode-hook 'stag-csharp-mode-hook)

#+END_SRC
*** emacs lisp (gettin' meta in here)
#+BEGIN_SRC emacs-lisp
(add-hook 'lisp-mode-hook 'stag-code-modes-hook)
(add-hook 'lisp-mode-hook 'paredit-mode)

(add-hook 'emacs-lisp-mode-hook 'stag-code-modes-hook)
(add-hook 'emacs-lisp-mode-hook 'paredit-mode)

(add-hook 'emacs-lisp-mode-hook 'turn-on-eldoc-mode)
(add-hook 'lisp-interaction-mode-hook 'turn-on-eldoc-mode)
(add-hook 'ielm-mode-hook 'turn-on-eldoc-mode)
#+END_SRC
*** CSS
#+BEGIN_SRC emacs-lisp
(defun stag-all-css-modes ()
  (css-mode)
  (rainbow-mode))

(add-to-list 'auto-mode-alist '("\\.css$" . stag-all-css-modes))
(add-to-list 'auto-mode-alist '("\\.scss$" . stag-all-css-modes))
#+END_SRC
*** HTML
Here are all the extensions where I want web-mode
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.jsp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
#+END_SRC

Also, I want to use auto-complete with the ac-html source when in web-mode
#+BEGIN_SRC emacs-lisp
(require 'web-mode)
(add-to-list 'web-mode-ac-sources-alist
             '("html" . (ac-source-html-attribute-value
                         ac-source-html-tag
                         ac-source-html-attribute)))
#+END_SRC
(setq web-mode-markup-indent-offset 4)
(setq web-mode-css-indent-offset 4)
(setq web-mode-code-indent-offset 4)
(setq web-mode-indent-style 4)
#+BEGIN_SRC emacs-lisp

#+END_SRC
*** Javascript
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '(".js$" . js2-mode))
(add-hook 'js2-mode-hook 'stag-code-modes-hook)
(add-hook 'js2-mode-hook 'ac-js2-mode)
#+END_SRC
*** Markdown
#+BEGIN_SRC emacs-lisp
(add-hook 'markdown-mode-hook 'turn-on-orgtbl)
#+END_SRC
*** Ruby (explain it all better)
There's a few extra things I want started when I open a Ruby buffer
#+BEGIN_SRC emacs-lisp
(defun stag-ruby-mode-hook ()
  (ruby-refactor-mode-launch)
  (inf-ruby-minor-mode)
  (modify-syntax-entry ?: ".") ;; Adds ":" to the word definition
  (rbenv-use-corresponding))
(add-hook 'enh-ruby-mode-hook 'stag-code-modes-hook)
(add-hook 'enh-ruby-mode-hook 'stag-ruby-mode-hook)
#+END_SRC

And I like projectile-rails to handle rails projects.
#+BEGIN_SRC emacs-lisp
(add-hook 'projectile-mode-hook 'projectile-rails-on)
#+END_SRC

What counts as a ruby buffer anyway? I like enh-ruby-mode better.
#+BEGIN_SRC emacs-lisp
(add-to-list 'interpreter-mode-alist '("ruby" . enh-ruby-mode))

(add-to-list 'auto-mode-alist '("\\.rb$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("Guardfile" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rake$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("\\.pryrc$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("Rakefile$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("Capfile$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("\\.ru$" . enh-ruby-mode))
#+END_SRC

And I like pry better than irb, so have inf-ruby use pry.
#+BEGIN_SRC emacs-lisp
(require 'inf-ruby)
(add-to-list 'inf-ruby-implementations '("pry" . "pry"))
(setq inf-ruby-default-implementation "pry")
(setq inf-ruby-first-prompt-pattern "^\\[[0-9]+\\] pry\\((.*)\\)> *")
(setq inf-ruby-prompt-pattern "^\\[[0-9]+\\] pry\\((.*)\\)[>*\"'] *")
#+END_SRC

I use yasnippets, and I've downloaded a collection of snippets from here: https://github.com/bmaland/yasnippet-ruby-mode
*** Rust
#+BEGIN_SRC emacs-lisp
(add-hook 'rust-mode-hook 'stag-code-modes-hook)
(add-hook 'rust-mode-hook 'flycheck-mode)
(add-hook 'rust-mode-hook 'flymake-mode)
#+END_SRC
*** Shells
#+BEGIN_SRC emacs-lisp
(setq explicit-bash-args '("--noediting" "--login" "-i"))

(require 'em-smart)

(require 'bash-completion)
(bash-completion-setup)

(defadvice ansi-term (after advise-ansi-term-coding-system)
    (set-buffer-process-coding-system 'utf-8-unix 'utf-8-unix))
(ad-activate 'ansi-term)
#+END_SRC
*** Slime
#+BEGIN_SRC emacs-lisp
  (load (expand-file-name "~/quicklisp/slime-helper.el"))
  ;; Replace "sbcl" with the path to your implementation
  (setq inferior-lisp-program "clisp")
#+END_SRC
*** SQL
auto-upcase SQL keywords as I type, please.
#+BEGIN_SRC emacs-lisp
(add-hook 'sql-mode-hook 'sqlup-mode)
(add-hook 'sql-interactive-mode-hook 'sqlup-mode)
#+END_SRC
*** Whitespace
#+BEGIN_SRC emacs-lisp
(require 'whitespace)
(setq whitespace-line-column 80) ;; limit line length
(setq whitespace-style '(face trailing tabs lines-tail))
(setq whitespace-global-modes '(not org-mode web-mode "Web"))
(global-whitespace-mode)
#+END_SRC
** Org-mode
You could argue that this should be somewhere else, but heck, org-mode is a BIG part of what I do with emacs...
*** TODO Org-table to Github-flavored markdown table (Add keybinding for custom function)
#+BEGIN_SRC emacs-lisp
;;; orgtbl-to-gfm conversion function
;; Usage Example:
;;
;; <!-- BEGIN RECEIVE ORGTBL ${1:YOUR_TABLE_NAME} -->
;; <!-- END RECEIVE ORGTBL $1 -->
;;
;; <!--
;; #+ORGTBL: SEND $1 orgtbl-to-gfm
;; | $0 |
;; -->

(defun orgtbl-to-gfm (table params)
  "Convert the Orgtbl mode TABLE to GitHub Flavored Markdown."
  (let* ((alignment (mapconcat (lambda (x) (if x "|--:" "|---"))
                               org-table-last-alignment ""))
         (params2
          (list
           :splice t
           :hline (concat alignment "|")
           :lstart "| " :lend " |" :sep " | ")))
    (orgtbl-to-generic table (org-combine-plists params2 params))))

(defun stag-insert-org-to-md-table (table-name)
  (interactive "*sEnter table name: ")
  (insert "<!---
#+ORGTBL: SEND " table-name " orgtbl-to-gfm

-->
<!--- BEGIN RECEIVE ORGTBL " table-name " -->
<!--- END RECEIVE ORGTBL " table-name " -->")
  (previous-line)
  (previous-line)
  (previous-line))

#+END_SRC
*** TODO Other stuff (break it down, explain it more)
#+BEGIN_SRC emacs-lisp
(setq org-src-fontify-natively t)
(add-to-list 'auto-mode-alist '(".org.txt$" . org-mode))

(setq org-directory "~/Google Drive/notes")
(setq org-default-notes-file (concat org-directory "/notes.org.txt"))
(define-key global-map "\C-cc" 'org-capture)

(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)

(setq org-startup-indented t)
(setq org-log-done 'time)

(setq org-todo-keywords '( "TODO(t)" "WAIT(w)" "|" "DONE" "CANCELED(c)"))
(setq org-tag-alist '(("@home" . ?h) ("@work" . ?w) ("family") ("wdi") ("strategy")  ("weiqi") ("ruby") ("lisp") ("emacs")))

(setq org-mobile-directory "~/Dropbox/orgnotes")
(setq org-mobile-inbox-for-pull "~/Google Drive/notes/from-mobile.org")
#+END_SRC

*** Left mouse-click to org-cycle, too
What? My hands aren't ALWAYS on the keyboard.
#+BEGIN_SRC emacs-lisp
(defun stag-click-to-cycle-org-visibility ()
  (local-set-key [mouse-1] 'org-cycle))
(add-hook 'org-mode-hook 'stag-click-to-cycle-org-visibility)
#+END_SRC
** General emacs config (no external packages)
*** Yes/No => y/n
#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC
*** Visual choices
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
(setq initial-scratch-message nil)
(show-paren-mode t)
(setq show-paren-delay 0)
(global-hl-line-mode t)
(setq column-number-mode t)
(setq ring-bell-function 'ignore)
(setq visible-bell t)
(setq system-uses-terminfo nil)
#+END_SRC

This shows the file path in the GUI header
#+BEGIN_SRC emacs-lisp
(setq-default frame-title-format '((:eval (if (buffer-file-name)
                                              (abbreviate-file-name (buffer-file-name)) "%f"))))
#+END_SRC
*** Backups
Centralize emacs backups.
#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
#+END_SRC
And I'm not super-worried about old backups and other such things, so I'll just tell emacs to stop worrying about it.
#+BEGIN_SRC emacs-lisp
(setq delete-old-versions -1)
(setq version-control t)
(setq vc-make-backup-files t)
(setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
#+END_SRC
*** History
Stolen from http://www.wisdomandwonder.com/wordpress/wp-content/uploads/2014/03/C3F.html#sec-10-3-2
#+BEGIN_SRC emacs-lisp
(setq savehist-file "~/.emacs.d/savehist")
(savehist-mode 1)
(setq history-length t)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history 1)
(setq savehist-additional-variables
      '(kill-ring
        search-ring
        regexp-search-ring))
#+END_SRC
*** TODO Window config (Put OSX stuff somewhere else)
I don't really care about any of the extra details - emacs helps me out enough in other ways.
#+BEGIN_SRC emacs-lisp
(when window-system
  (tooltip-mode -1)
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1))
#+END_SRC

Although of course if you're on OSX, at least the menu bar can be enabled since the mighty OSX top bar won't ever disappear.
And I've also added other OSX-specific stuff here... For now.
#+BEGIN_SRC emacs-lisp
(when (memq window-system '(mac ns))
  (exec-path-from-shell-initialize)
  (setq ns-use-srgb-colorspace t)
  (menu-bar-mode t))
#+END_SRC
*** Interacting with text
**** Use visual-line-mode
#+BEGIN_SRC emacs-lisp
(remove-hook 'text-mode-hook #'turn-on-auto-fill)
(add-hook 'text-mode-hook 'turn-on-visual-line-mode)
#+END_SRC
**** Redefine kill-region and backward-kill-word
Because ... I'm used to being in a shell, you know?
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-w") 'backward-kill-word)
(global-set-key (kbd "C-x C-k") 'kill-region)
#+END_SRC
**** Move down real line by real line
#+BEGIN_SRC emacs-lisp
(setq line-move-visual nil)
#+END_SRC
**** Sentences end with a single space
#+BEGIN_SRC emacs-lisp
(setq sentence-end-double-space nil)
#+END_SRC
**** Text size
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
#+END_SRC
**** Inserting new lines before/after current one
#+BEGIN_SRC emacs-lisp
(defun stag-insert-line-below ()
  "Insert and auto-indent line below cursor, like in vim."
  (interactive)
  (move-end-of-line 1)
  (open-line 1)
  (next-line)
  (indent-for-tab-command))

(defun stag-insert-line-above ()
  "Insert and auto-indent line above cursor, like in vim."
  (interactive)
  (previous-line)
  (move-end-of-line 1)
  (stag-insert-line-below))

(global-set-key (kbd "C-o") 'stag-insert-line-below)
(global-set-key (kbd "C-M-o") 'stag-insert-line-above)
#+END_SRC
*** UTF-8
#+BEGIN_SRC emacs-lisp
;; Activate UTF-8 mode:
(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

;; 2013-12-10 IRC #Emacs
(set-clipboard-coding-system 'utf-8)

;; http://www.masteringemacs.org/articles/2012/08/09/working-coding-systems-unicode-emacs/
;; in addition to the lines above:

(set-default-coding-systems 'utf-8)
;; backwards compatibility as default-buffer-file-coding-system
;; is deprecated in 23.2.
(if (boundp 'buffer-file-coding-system)
    (setq-default buffer-file-coding-system 'utf-8)
  (setq default-buffer-file-coding-system 'utf-8))
;; Treat clipboard input as UTF-8 string first; compound text next, etc.
(setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING))
#+END_SRC
*** Buffer management
I like unique buffer names. Enter uniquify.
#+BEGIN_SRC emacs-lisp
(require 'uniquify)
(setq
  uniquify-buffer-name-style 'post-forward
  uniquify-separator ":")
#+END_SRC
Also, ibuffer is nicer than plain-old buffer window
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer-other-window)
(setq ibuffer-default-sorting-mode 'major-mode)
#+END_SRC
*** Window management
Taken from http://www.reddit.com/r/emacs/comments/25v0eo/you_emacs_tips_and_tricks/chldury
#+BEGIN_SRC emacs-lisp
(defun stag-vsplit-last-buffer (prefix)
  (interactive "p")
  (split-window-vertically)
  (other-window 1 nil)
  (unless prefix
          (switch-to-next-buffer)))

(defun stag-hsplit-last-buffer (prefix)
  (interactive "p")
  (split-window-horizontally)
  (other-window 1 nil)
  (unless prefix
    (switch-to-next-buffer)))

(global-set-key (kbd "C-x 2") 'stag-vsplit-last-buffer)
(global-set-key (kbd "C-x 3") 'stag-hsplit-last-buffer)
#+END_SRC
*** Scrolling
#+BEGIN_SRC emacs-lisp
(setq scroll-margin 5
      scroll-preserve-screen-position 1)
#+END_SRC
** Calendar, dates, times
#+BEGIN_SRC emacs-lisp
(setq calendar-week-start-day 1) ;; Monday
#+END_SRC
*** Diary
#+BEGIN_SRC emacs-lisp
(setq diary-file "~/Google Drive/diary")

(setq view-diary-entries-initially t
      mark-diary-entries-in-calendar t
      number-of-diary-entries 7)
(add-hook 'diary-display-hook 'diary-fancy-display)
(add-hook 'today-visible-calendar-hook 'calendar-mark-today)
#+END_SRC
*** calfw, the calendar framework
#+BEGIN_SRC emacs-lisp
(require 'calfw)
(require 'calfw-cal)
(require 'calfw-ical)
(require 'calfw-org)

(setq cfw:fchar-junction ?╋
      cfw:fchar-vertical-line ?┃
      cfw:fchar-horizontal-line ?━
      cfw:fchar-left-junction ?┣
      cfw:fchar-right-junction ?┫
      cfw:fchar-top-junction ?┯
      cfw:fchar-top-left-corner ?┏
      cfw:fchar-top-right-corner ?┓)
#+END_SRC

Here is a sample function where you could, for instance, put your Google Calendar information (mostly so I remember how to create the secret file on a new computer).

#+BEGIN_QUOTE
(defun stag-calendar ()
  (interactive)
  (cfw:open-calendar-buffer
   :contents-sources
   (list
    (cfw:org-create-source "Green")
    (cfw:cal-create-source "Orange")
    (cfw:ical-create-source "gcal" "gcal-ics-link" "Blue")
    )))
#+END_QUOTE
** File system browsing (dired)
dired-jump is awesome
#+BEGIN_SRC emacs-lisp
(require 'dired-x)
#+END_SRC
#+BEGIN_SRC emacs-lisp
(setq-default dired-listing-switches "-alhv")

;; Auto-refresh silently
(setq global-auto-revert-non-file-buffers t)
(setq auto-revert-verbose nil)
#+END_SRC

It's also nice to have dired with M-< and M-> take you to first and last file
#+BEGIN_SRC emacs-lisp
(require 'dired)
(defun dired-back-to-top ()
  (interactive)
  (beginning-of-buffer)
  (next-line 2))

(define-key dired-mode-map
  (vector 'remap 'beginning-of-buffer) 'dired-back-to-top)

(defun dired-jump-to-bottom ()
  (interactive)
  (end-of-buffer)
  (next-line -1))

(define-key dired-mode-map
  (vector 'remap 'end-of-buffer) 'dired-jump-to-bottom)
#+END_SRC
** Interacting with emacs
*** Interface
I use IDO and I like it a lot. flx-ido, especially, is basically heaven.
#+BEGIN_SRC emacs-lisp
(ido-mode 1)
(ido-ubiquitous 1)
(ido-vertical-mode 1)
(flx-ido-mode 1)
(add-to-list 'ido-ignore-files "\\.DS_Store")
(setq ido-use-faces t
      ido-enable-prefix nil
      ido-enable-flex-matching t
      ido-case-fold t ;; ignore case
      ido-create-new-buffer 'always ;; easily create files
      ido-use-filename-at-point nil ;; don't try to be smart
)

(setq ido-auto-merge-delay-time 7) ;; Default: 0.7
#+END_SRC
*** Fuzzy matching
Enter smex. I like typing "plp" to get to "package-list-packages".
#+BEGIN_SRC emacs-lisp
(smex-initialize)
(global-set-key (kbd "C-x C-m") 'smex)
(global-set-key (kbd "C-x m") 'smex-major-mode-commands)
(setq smex-auto-update t)
#+END_SRC
*** Fonts and stuff
The world begins with this function I found online somewhere. Before I kept track of things.
#+BEGIN_SRC emacs-lisp
(defun stag-what-face (pos)
  (interactive "d")
  (let ((face (or (get-char-property pos 'read-face-name)
                  (get-char-property pos 'face))))
    (if face (message "Face: %s" face) (message "No face at %d" pos))))
#+END_SRC
